# Generated by Django 5.0 on 2024-01-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey'),
        ),
    ]
