# Generated by Django 5.0 on 2024-01-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_response_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
